### ISSUE TITLE
The jenkins build fails pushing to docker hub

### ISSUE THREAD

**Issue by pvalsecc** [camptocamp/docker-postgis#5]
Must be missing some authentication or something:
```
+ docker push camptocamp/postgis:9.4
The push refers to a repository [docker.io/camptocamp/postgis]
...
unauthorized: authentication required
```

**Comment by raphink** [comment]
Yes, https://github.com/camptocamp/docker-postgis/blob/master/Jenkinsfile#L25 is the bit that retrieves the authentication info from Jenkins
