### ISSUE TITLE
Alpine Build

### ISSUE THREAD

**Issue by sushantdhiman** [camptocamp/docker-postgis#6]

**Comment by pvalsecc** [comment]
Why?

**Comment by sushantdhiman** [comment]
Currently image take about `547 MB` space, while `kiasaki/alpine-postgres` take only `25.7 MB`. I have noticed alpine images performed better on our CI tests as well.

There should be no problem in going lean

**Comment by pvalsecc** [comment]
Installing the postgis extension and all its dependencies is what takes most of the room: 283MB
Then, you have postgresql from the base image (official) which takes 116MB
The base OS is around 123MB

So, the biggest contribution to image size, here is installing postgis.

Now, I have no experience with Alpine Linux. If you want to experiment, I have no problem accepting PRs.

**Comment by sushantdhiman** [comment]
Thanks I have no need for an alpine build now (I've created an image as per my requirements)
