### ISSUE TITLE
Version 9.4 installs postgis 2.3 dependencies

### ISSUE THREAD

**Issue by sebastian-r-schmidt** [camptocamp/docker-postgis#7]
The 9.4 version with Postgis 2.1 is not working correctly.
When looking at the build logs at 
https://hub.docker.com/r/camptocamp/postgis/builds/bipsuibpafsrc67vfscix5j/ 
I can see that `postgresql-9.4-postgis-2.3-scripts` is installed via apt

As a consequence, `create extension postgis 
`fails

**Comment by imoon** [comment]
Confirmed. @sebastian-r-schmidt did you find a work-around?

**Comment by sebastian-r-schmidt** [comment]
I did not manage to run 9.4/2.1 correctly with this image. 
I switched to your 9.5 version as a workaround for my local development environment.

**Comment by imoon** [comment]
Ok thanks. I don't manage this repo, but was trying to use it for a legacy project that makes use of this image and ran into this issue. Basically, it has broken our environment. I ended up using [mdillon/postgis](https://github.com/appropriate/docker-postgis):9.4

**Comment by yjacolin** [comment]
PostGIS 2.1 is not available anymore from postgres repository. I updated to postgis 2.3, built and container work as expected.
